CREATE TABLE IF NOT EXISTS applications (
            id SERIAL PRIMARY KEY,
            full_name VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL UNIQUE,
            mobile VARCHAR(20) NOT NULL,
            dob DATE NOT NULL,
            parent_name VARCHAR(255) NOT NULL,
            gender VARCHAR(50) NOT NULL,
            nationality VARCHAR(100) NOT NULL,
            marital_status VARCHAR(50),
            current_address TEXT NOT NULL,
            permanent_address TEXT NOT NULL,
            state VARCHAR(100) NOT NULL,
            city VARCHAR(100) NOT NULL,
            zipcode VARCHAR(20) NOT NULL,
            emergency_contact VARCHAR(255) NOT NULL,
            ssc_board VARCHAR(255) NOT NULL,
            ssc_year INTEGER NOT NULL,
            ssc_percentage VARCHAR(10) NOT NULL,
            intermediate_board VARCHAR(255),
            intermediate_year INTEGER,
            intermediate_percentage VARCHAR(10),
            college_name VARCHAR(255),
            qualification VARCHAR(255),
            branch VARCHAR(255),
            graduation_year INTEGER,
            graduation_percentage VARCHAR(10),
            additional_education JSONB,
            job_role VARCHAR(255) NOT NULL,
            preferred_location VARCHAR(255) NOT NULL,
            notice_period VARCHAR(100) NOT NULL,
            expected_salary NUMERIC,
            skills TEXT NOT NULL,
            experience_status VARCHAR(50) NOT NULL,
            years_experience INTEGER,
            company_name VARCHAR(255),
            designation VARCHAR(255),
            work_location VARCHAR(255),
            start_date VARCHAR(20),
            end_date VARCHAR(20),
            last_salary NUMERIC,
            alt_mobile VARCHAR(20),
            linkedin VARCHAR(255),
            github VARCHAR(255),
            certifications TEXT,
            reference_name VARCHAR(255),
            reference_email VARCHAR(255),
            resume_path VARCHAR(255) NOT NULL,
            cover_letter_path VARCHAR(255),
            submission_date TIMESTAMP NOT NULL,
            status VARCHAR(50) DEFAULT 'Pending'
        );